### ISSUE TITLE
Activation not possible within a shadow dom environment. So under Web Components.

### ISSUE THREAD

**Issue by dobexx** [JiHong88/SunEditor#372] opened 2020-05-12 07:32 UTC
Hello @JiHong88 ,

Thank you for the great product. Excellent work. 👌

Currently I am not able to accommodate the editor of a Shadow Dom environment. When activating and embedding the SunEditor CSS the cursor of the editor cannot be used.  

Does this have a reason? Am I doing something wrong in the configuration?
Unfortunately I could not find anything in the documentation.

**Comment by JiHong88** [comment] 2020-05-22 07:25
Hi,
This issue is not reproduced.
Can you show the code that generated the editor?

**Comment by JiHong88** [comment] 2020-05-23 12:40
Does this issue only occur in Safari?

**Comment by JiHong88** [comment] 2020-05-23 13:54
Safari is not support `getSelection` of the shadow root.😭

**Comment by dobexx** [comment] 2020-05-23 13:59
Hmm i have see now an other pull request with the same topic.

https://github.com/JiHong88/SunEditor/pull/365

Currently we have tested in blink engine only.

**Comment by dobexx** [comment] 2020-05-23 14:09
Maybe this helps within a certain Safari version spectrum?

https://github.com/jsturgill/shadow-root-get-selection-polyfill

**Comment by dobexx** [comment] 2020-05-23 14:11
I'm going to put together a code snippet on Stackblitz or JSBin with Shadow Dom and the 2.29 and report them.  I think next week.

Greetings from Germany.

**Comment by JiHong88** [comment] 2020-05-23 14:54
https://github.com/jsturgill/shadow-root-get-selection-polyfill
The current editor's code is no different from this.
However, it does not work properly in Safari.

**Comment by dobexx** [comment] 2020-05-28 08:12
I have now built a code snippet with switchable shadow dom. So with the current 2.29 there are no errors in the basic setup. 

https://stackblitz.com/edit/vanilla-webcomponent-suneditor?file=elements%2Fmy-element.js

I will continue to observe it now. From my point of view the ticket can be closed for now.

**Comment by JiHong88** [comment] 2020-06-07 18:22
Yes I will find a way too.
But, there seems to be no way at this time.
I close this issue.

**Closed by JiHong88** 2020-06-07 18:22 UTC
Labels: bug

**Comment by lucsoft** [comment] 2024-08-05 12:43
Follow up: getSelection in ShadowRoot is not a Standard API and the getComposedRanges should be used instead. But Only Firefox and Safari supports this feature.

**Comment by GrzegorzKazana** [comment] 2026-06-25 08:37
Suggested hack/fix/workaround:
https://github.com/JiHong88/suneditor/issues/1543#issuecomment-4797360377
